In [1]:
import numpy as np
import pandas as pd
import scanpy as sc
import anndata
import scipy as scp
import numpy.ma as ma

In [2]:
folderWithFiles='/media/kush/2TB HDD A/kallisto_bustools_getting_started/bus_output_07/spliced'

In [3]:
output_file=open('/media/kush/2TB HDD A/kallisto_bustools_getting_started/bus_output_07/spliced/remake.genes.txt','w')

In [4]:
data=pd.read_csv('/media/kush/2TB HDD A/kallisto_bustools_getting_started/cDNA_introns.t2g.txt',sep='\t',header=None)

In [5]:
data.columns=["Number","GID","Gene Code"]

In [6]:
data.drop_duplicates(subset ="GID", keep = "first", inplace = True) 

In [7]:
geneCodeData=data["Gene Code"]

In [8]:
dataList=list(geneCodeData)

In [9]:
for i in dataList:
    output_file.write(i+"\n")

In [10]:
output_file.close()

In [11]:
matrix=sc.read_mtx(folderWithFiles+'/s.mtx')

In [12]:
barcodes=pd.read_csv(folderWithFiles+'/s.barcodes.txt',header=None)

In [13]:
genes=pd.read_csv(folderWithFiles+'/remake.genes.txt',header=None)

In [14]:
matrix.obs.index = barcodes[0].values

In [15]:
matrix.var.index = genes[0].values

In [16]:
dfMatrix=matrix.to_df()

In [17]:
dfMatrix

DDX11L1  WASH7P  MIR6859-1  MIR1302-2HG  MIR1302-2  FAM138A  \
AAACCTGAGAAACCTA      0.0     0.0        0.0          0.0        0.0      0.0   
AAACCTGAGAAACGAG      0.0     0.0        0.0          0.0        0.0      0.0   
AAACCTGAGAAACGCC      0.0     0.0        0.0          0.0        0.0      0.0   
AAACCTGAGAACAATC      0.0     0.0        0.0          0.0        0.0      0.0   
AAACCTGAGAAGGTGA      0.0     0.0        0.0          0.0        0.0      0.0   
...                   ...     ...        ...          ...        ...      ...   
TTTGTCATCTTGTATC      0.0     0.0        0.0          0.0        0.0      0.0   
TTTGTCATCTTGTTTG      0.0     0.0        0.0          0.0        0.0      0.0   
TTTGTCATCTTTACAC      0.0     0.0        0.0          0.0        0.0      0.0   
TTTGTCATCTTTACGT      0.0     0.0        0.0          0.0        0.0      0.0   
TTTGTCATCTTTAGTC      0.0     0.0        0.0          0.0        0.0      0.0   

                  OR4G4P  OR4G11P  OR4F5  AL627309  ...  AC023491  AC023491  \
AAACCTGAGAAACCTA     0.0      0.0    0.0       0.0  ...       0.0       0.0   
AAACCTGAGAAACGAG     0.0      0.0    0.0       0.0  ...       0.0       0.0   
AAACCTGAGAAACGCC     0.0      0.0    0.0       0.0  ...       0.0       0.0   
AAACCTGAGAACAATC     0.0      0.0    0.0       0.0  ...       0.0       0.0   
AAACCTGAGAAGGTGA     0.0      0.0    0.0       0.0  ...       0.0       0.0   
...                  ...      ...    ...       ...  ...       ...       ...   
TTTGTCATCTTGTATC     0.0      0.0    0.0       0.0  ...       0.0       0.0   
TTTGTCATCTTGTTTG     0.0      0.0    0.0       0.0  ...       0.0       0.0   
TTTGTCATCTTTACAC     0.0      0.0    0.0       0.0  ...       0.0       0.0   
TTTGTCATCTTTACGT     0.0      0.0    0.0       0.0  ...       0.0       0.0   
TTTGTCATCTTTAGTC     0.0      0.0    0.0       0.0  ...       0.0       0.0   

                  RF01518  RNA5-8SN2  RF01518  RNA5-8SN2  AC007325  AC007325  \
AAACCTGAGAAACCTA      0.0        0.0      0.0        0.0       0.0       0.0   
AAACCTGAGAAACGAG      0.0        0.0      0.0        0.0       0.0       0.0   
AAACCTGAGAAACGCC      0.0        0.0      0.0        0.0       0.0       0.0   
AAACCTGAGAACAATC      0.0        0.0      0.0        0.0       0.0       0.0   
AAACCTGAGAAGGTGA      0.0        0.0      0.0        0.0       0.0       0.0   
...                   ...        ...      ...        ...       ...       ...   
TTTGTCATCTTGTATC      0.0        0.0      0.0        0.0       0.0       0.0   
TTTGTCATCTTGTTTG      0.0        0.0      0.0        0.0       0.0       0.0   
TTTGTCATCTTTACAC      0.0        0.0      0.0        0.0       0.0       0.0   
TTTGTCATCTTTACGT      0.0        0.0      0.0        0.0       0.0       0.0   
TTTGTCATCTTTAGTC      0.0        0.0      0.0        0.0       0.0       0.0   

                  AC007325  AC007325  
AAACCTGAGAAACCTA       0.0       0.0  
AAACCTGAGAAACGAG       0.0       0.0  
AAACCTGAGAAACGCC       0.0       0.0  
AAACCTGAGAACAATC       0.0       0.0  
AAACCTGAGAAGGTGA       0.0       0.0  
...                    ...       ...  
TTTGTCATCTTGTATC       0.0       0.0  
TTTGTCATCTTGTTTG       0.0       0.0  
TTTGTCATCTTTACAC       0.0       0.0  
TTTGTCATCTTTACGT       0.0       0.0  
TTTGTCATCTTTAGTC       0.0       0.0  

[299566 rows x 64792 columns]

In [18]:
npMatrix=dfMatrix.to_numpy()

In [19]:
npMatrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [20]:
npMatrixSum=np.sum(npMatrix,axis=1)

In [23]:
npMatrixSum

array([1., 1., 2., ..., 1., 2., 7.], dtype=float32)

In [22]:
npMatrixSumBoolean=npMatrixSum>3

In [24]:
npMatrixSumBoolean

array([False, False, False, ..., False, False,  True])

In [28]:
newShape=np.sum(npMatrixSumBoolean)
newShape

In [29]:
npMatrixMax=np.sum(npMatrix,axis=1)>3

In [43]:
np.column_stack((npMatrixMax,npMatrixMax,npMatrixMax))

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       ...,
       [False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [21]:
index=-1
for x in np.nditer(npMatrixSum):
    index=index+1
    print(index)
    if(x<3):
        np.delete(npMatrix,index,None)
    if(index>20):
        print(matrix.shape)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
(299566, 64792)
22


KeyboardInterrupt: 

In [22]:
npMatrix.shape

(299566, 64792)

In [19]:
reducedMatrix=dfMatrix[['AC007325']]

In [20]:
reducedMatrix

AC007325  AC007325  AC007325  AC007325
AAACCTGAGAAACCTA       0.0       0.0       0.0       0.0
AAACCTGAGAAACGAG       0.0       0.0       0.0       0.0
AAACCTGAGAAACGCC       0.0       0.0       0.0       0.0
AAACCTGAGAACAATC       0.0       0.0       0.0       0.0
AAACCTGAGAAGGTGA       0.0       0.0       0.0       0.0
...                    ...       ...       ...       ...
TTTGTCATCTTGTATC       0.0       0.0       0.0       0.0
TTTGTCATCTTGTTTG       0.0       0.0       0.0       0.0
TTTGTCATCTTTACAC       0.0       0.0       0.0       0.0
TTTGTCATCTTTACGT       0.0       0.0       0.0       0.0
TTTGTCATCTTTAGTC       0.0       0.0       0.0       0.0

[299566 rows x 4 columns]

In [22]:
betterReducedMatrix=reducedMatrix.groupby(reducedMatrix.columns,axis=1).sum()

In [23]:
betterReducedMatrix

AC007325
AAACCTGAGAAACCTA       0.0
AAACCTGAGAAACGAG       0.0
AAACCTGAGAAACGCC       0.0
AAACCTGAGAACAATC       0.0
AAACCTGAGAAGGTGA       0.0
...                    ...
TTTGTCATCTTGTATC       0.0
TTTGTCATCTTGTTTG       0.0
TTTGTCATCTTTACAC       0.0
TTTGTCATCTTTACGT       0.0
TTTGTCATCTTTAGTC       0.0

[299566 rows x 1 columns]

In [26]:
type(betterReducedMatrix)

pandas.core.frame.DataFrame

In [29]:
sc.AnnData(betterReducedMatrix).write_h5ad('/media/kush/2TB HDD A/kallisto_bustools_getting_started/bus_output_07/spliced/est.h5ad',compression="gzip")

In [30]:
# run this one: sc.AnnData(dfMatrix.groupby(dfMatrix.columns,axis=1).sum()).write_h5ad('/media/kush/2TB HDD A/kallisto_bustools_getting_started/bus_output_07/spliced/betterTest.h5ad',compression="gzip")