In [30]:
import numpy as np
import pandas as pd
import scanpy as sc
import anndata
import scipy as scp
import numpy.ma as ma

In [31]:
folderWithFiles='/media/kush/2TB HDD A/kallisto_bustools_getting_started/bus_output_07/spliced'

In [32]:
output_file=open('/media/kush/2TB HDD A/kallisto_bustools_getting_started/bus_output_07/spliced/remake.genes.txt','w')

In [33]:
data=pd.read_csv('/media/kush/2TB HDD A/kallisto_bustools_getting_started/cDNA_introns.t2g.txt',sep='\t',header=None)

In [34]:
data.columns=["Number","GID","Gene Code"]

In [35]:
data.drop_duplicates(subset ="GID", keep = "first", inplace = True) 

In [36]:
geneCodeData=data["Gene Code"]

In [37]:
dataList=list(geneCodeData)

In [38]:
for i in dataList:
    output_file.write(i+"\n")

In [39]:
output_file.close()

In [40]:
matrix=sc.read_mtx(folderWithFiles+'/s.mtx')

In [41]:
barcodes=pd.read_csv(folderWithFiles+'/s.barcodes.txt',header=None)

In [42]:
genes=pd.read_csv(folderWithFiles+'/remake.genes.txt',header=None)

In [43]:
matrix.obs.index = barcodes[0].values

In [44]:
matrix.var.index = genes[0].values

In [45]:
dfMatrix=matrix.to_df()

In [46]:
dfMatrix

DDX11L1  WASH7P  MIR6859-1  MIR1302-2HG  MIR1302-2  FAM138A  \
AAACCTGAGAAACCTA      0.0     0.0        0.0          0.0        0.0      0.0   
AAACCTGAGAAACGAG      0.0     0.0        0.0          0.0        0.0      0.0   
AAACCTGAGAAACGCC      0.0     0.0        0.0          0.0        0.0      0.0   
AAACCTGAGAACAATC      0.0     0.0        0.0          0.0        0.0      0.0   
AAACCTGAGAAGGTGA      0.0     0.0        0.0          0.0        0.0      0.0   
...                   ...     ...        ...          ...        ...      ...   
TTTGTCATCTTGTATC      0.0     0.0        0.0          0.0        0.0      0.0   
TTTGTCATCTTGTTTG      0.0     0.0        0.0          0.0        0.0      0.0   
TTTGTCATCTTTACAC      0.0     0.0        0.0          0.0        0.0      0.0   
TTTGTCATCTTTACGT      0.0     0.0        0.0          0.0        0.0      0.0   
TTTGTCATCTTTAGTC      0.0     0.0        0.0          0.0        0.0      0.0   

                  OR4G4P  OR4G11P  OR4F5  AL627309  ...  AC023491  AC023491  \
AAACCTGAGAAACCTA     0.0      0.0    0.0       0.0  ...       0.0       0.0   
AAACCTGAGAAACGAG     0.0      0.0    0.0       0.0  ...       0.0       0.0   
AAACCTGAGAAACGCC     0.0      0.0    0.0       0.0  ...       0.0       0.0   
AAACCTGAGAACAATC     0.0      0.0    0.0       0.0  ...       0.0       0.0   
AAACCTGAGAAGGTGA     0.0      0.0    0.0       0.0  ...       0.0       0.0   
...                  ...      ...    ...       ...  ...       ...       ...   
TTTGTCATCTTGTATC     0.0      0.0    0.0       0.0  ...       0.0       0.0   
TTTGTCATCTTGTTTG     0.0      0.0    0.0       0.0  ...       0.0       0.0   
TTTGTCATCTTTACAC     0.0      0.0    0.0       0.0  ...       0.0       0.0   
TTTGTCATCTTTACGT     0.0      0.0    0.0       0.0  ...       0.0       0.0   
TTTGTCATCTTTAGTC     0.0      0.0    0.0       0.0  ...       0.0       0.0   

                  RF01518  RNA5-8SN2  RF01518  RNA5-8SN2  AC007325  AC007325  \
AAACCTGAGAAACCTA      0.0        0.0      0.0        0.0       0.0       0.0   
AAACCTGAGAAACGAG      0.0        0.0      0.0        0.0       0.0       0.0   
AAACCTGAGAAACGCC      0.0        0.0      0.0        0.0       0.0       0.0   
AAACCTGAGAACAATC      0.0        0.0      0.0        0.0       0.0       0.0   
AAACCTGAGAAGGTGA      0.0        0.0      0.0        0.0       0.0       0.0   
...                   ...        ...      ...        ...       ...       ...   
TTTGTCATCTTGTATC      0.0        0.0      0.0        0.0       0.0       0.0   
TTTGTCATCTTGTTTG      0.0        0.0      0.0        0.0       0.0       0.0   
TTTGTCATCTTTACAC      0.0        0.0      0.0        0.0       0.0       0.0   
TTTGTCATCTTTACGT      0.0        0.0      0.0        0.0       0.0       0.0   
TTTGTCATCTTTAGTC      0.0        0.0      0.0        0.0       0.0       0.0   

                  AC007325  AC007325  
AAACCTGAGAAACCTA       0.0       0.0  
AAACCTGAGAAACGAG       0.0       0.0  
AAACCTGAGAAACGCC       0.0       0.0  
AAACCTGAGAACAATC       0.0       0.0  
AAACCTGAGAAGGTGA       0.0       0.0  
...                    ...       ...  
TTTGTCATCTTGTATC       0.0       0.0  
TTTGTCATCTTGTTTG       0.0       0.0  
TTTGTCATCTTTACAC       0.0       0.0  
TTTGTCATCTTTACGT       0.0       0.0  
TTTGTCATCTTTAGTC       0.0       0.0  

[299566 rows x 64792 columns]

In [47]:
npMatrix=dfMatrix.to_numpy()

In [48]:
npMatrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [49]:
npMatrix.shape

(299566, 64792)

In [50]:
npMatrixSum=np.sum(npMatrix,axis=1)

In [59]:
npMatrixSum

array([1., 1., 2., ..., 1., 2., 7.], dtype=float32)

In [60]:
npMatrixReduced=npMatrix[:,:1]

In [75]:
npMatrixReduced

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [77]:
npMatrixSumColumn=npMatrixSum.reshape(-1,1)

In [78]:
npMatrixSumColumn

array([[1.],
       [1.],
       [2.],
       ...,
       [1.],
       [2.],
       [7.]], dtype=float32)

In [62]:
print(np.append(npMatrixReduced,npMatrixSum,axis=1))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

array([1., 1., 2., ..., 1., 2., 7.], dtype=float32)

In [52]:
npMatrixMax=np.sum(npMatrix,axis=1)>3

In [53]:
npMatrixMax

array([False, False, False, ..., False, False,  True])

In [54]:
npStack=npMatrixMax
for x in range(0,16):
    npStack=np.column_stack((npStack,npStack))

In [55]:
npStack.shape

(299566, 65536)

In [56]:
npStackReduced=npStack[:,:-744]

In [57]:
npStackReduced

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [ True,  True,  True, ...,  True,  True,  True]])

In [58]:
npMatrix.shape

(299566, 64792)